source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'Shiftgram' do
     pod 'Alamofire', '~> 4.6'
     pod 'AWSCognito'
     pod 'AWSCognitoIdentityProvider'
     pod 'AWSS3'
     pod 'Firebase/Core'
     pod 'Firebase/Storage'
     pod 'Firebase/Auth'
     pod 'Firebase/Database'
     pod 'Firebase/Firestore'
     pod 'JSQMessagesViewController'
     pod "ROGoogleTranslate"
     pod 'TwilioVideo'
end
