source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'Shiftgram' do
    pod 'Alamofire', '~> 4.6'
     pod 'AWSCognito'
     pod 'AWSCognitoIdentityProvider'
     pod 'AWSS3'
     pod 'Firebase/Core'
     pod 'Firebase/Storage'
     pod 'Firebase/Auth'
     pod 'Firebase/Database'
     pod 'Firebase/Firestore'
     pod 'JSQMessagesViewController'
     pod "ROGoogleTranslate"
     pod 'MessageKit'
post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == 'MessageKit'
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '4.0'
              end
          end
      end
  end
end
