source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'Shiftgram' do
    pod 'Alamofire', '~> 4.6'
     pod 'AWSCognito'
     pod 'AWSCognitoIdentityProvider'
     pod 'AWSS3'
end
